/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        txtchoinhanh = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        txtchoivoimay = new javax.swing.JRadioButtonMenuItem();
        txtbangxephang = new javax.swing.JRadioButtonMenuItem();
        txtgioithieu = new javax.swing.JRadioButtonMenuItem();
        txtdangxuat = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        txtNickname = new javax.swing.JMenuItem();
        txtsovandachoi = new javax.swing.JMenuItem();
        txtsovanthang = new javax.swing.JMenuItem();
        txtdiem = new javax.swing.JMenuItem();
        txtxephang = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        txtchoinhanh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtchoinhanh.setText("TRANG CHỦ");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Chơi nhanh");
        txtchoinhanh.add(jRadioButtonMenuItem1);

        txtchoivoimay.setSelected(true);
        txtchoivoimay.setText("Chơi với máy");
        txtchoinhanh.add(txtchoivoimay);

        txtbangxephang.setSelected(true);
        txtbangxephang.setText("Bảng xếp hạng");
        txtchoinhanh.add(txtbangxephang);

        txtgioithieu.setSelected(true);
        txtgioithieu.setText("Giới thiệu");
        txtgioithieu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtgioithieuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtchoinhanh.add(txtgioithieu);

        txtdangxuat.setSelected(true);
        txtdangxuat.setText("Đăng xuất");
        txtchoinhanh.add(txtdangxuat);

        jMenuBar1.add(txtchoinhanh);

        jMenu2.setText("THÔNG TIN NGƯỜI CHƠI");

        txtNickname.setText("Nickname");
        txtNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicknameActionPerformed(evt);
            }
        });
        jMenu2.add(txtNickname);

        txtsovandachoi.setText("Số ván đã chơi");
        jMenu2.add(txtsovandachoi);

        txtsovanthang.setText("Số ván thắng");
        jMenu2.add(txtsovanthang);

        txtdiem.setText("Điểm");
        jMenu2.add(txtdiem);

        txtxephang.setText("Xếp hạng");
        jMenu2.add(txtxephang);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(534, 534, 534))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicknameActionPerformed

    private void txtgioithieuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtgioithieuAncestorAdded
         txtgioithieu.addActionListener((ActionEvent e) -> {
       JOptionPane.showMessageDialog(rootPane, ""
               + "Cờ ca-rô (hay sọc ca-rô) là một trò chơi dân gian khá phổ biến ở Việt Nam.\n"
               + " Đây là trò chơi trí tuệ lý tưởng cho những bạn học sinh tiểu học và trung học.\n"
               + " Trò chơi không cần yêu cầu khắt khe về luật và phương tiện chơi,\n "
               + "vì vậy trò này được mọi người ưa chuộng và phù hợp với mọi lứa tuổi.\n"
               +"Luật chơi cờ caro khá đơn giản, nhiệm vụ của mỗi ngườin\n"
               + " chơi cờ caro đó là đạt được một đường thẳng\n"
               + "đường chéo, đường ngang với 5 ô nhanh nhất.\n"
               + " Tuy nhiên, chỉ cần người chơi nào có thể đạt 4 nước mà bị chặn 1 đầu\n"
               + " hoặc không bị chặn hai đầu là đã có thể chiến thắng.\n");
   });    
    }//GEN-LAST:event_txtgioithieuAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem txtNickname;
    private javax.swing.JRadioButtonMenuItem txtbangxephang;
    private javax.swing.JMenu txtchoinhanh;
    private javax.swing.JRadioButtonMenuItem txtchoivoimay;
    private javax.swing.JRadioButtonMenuItem txtdangxuat;
    private javax.swing.JMenuItem txtdiem;
    private javax.swing.JRadioButtonMenuItem txtgioithieu;
    private javax.swing.JMenuItem txtsovandachoi;
    private javax.swing.JMenuItem txtsovanthang;
    private javax.swing.JMenuItem txtxephang;
    // End of variables declaration//GEN-END:variables
}
